---
name: Tests
on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ckan-version: ["2.10", 2.9]

    name: Test on CKAN ${{ matrix.ckan-version }}
    runs-on: ubuntu-latest
    container: drevops/ci-runner:23.12.0
    env:
      CKAN_VERSION: ${{ matrix.ckan-version }}

    steps:
      # Patch https://github.com/actions/runner/issues/863
      - name: Preserve $HOME set in the container
        run: echo HOME=/root >> "$GITHUB_ENV"

      - uses: actions/checkout@v4
        timeout-minutes: 2

      - name: Build
        run: bin/build.sh
        timeout-minutes: 15

      - name: Test
        run: bin/test.sh
        timeout-minutes: 20

      - name: Retrieve logs
        if: always()
        run: ahoy logs
        timeout-minutes: 5

      - name: Retrieve screenshots
        if: failure()
        run: bin/process-artifacts.sh
        timeout-minutes: 1

      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: CKAN ${{ matrix.ckan-version }} screenshots
          path: /tmp/artifacts/behave/screenshots
        timeout-minutes: 1
